package:
  name: pypy-llvmlite
  # GIT_DESCRIBE_TAG may not be set
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').lstrip('v') }}

source:
  # Using the local source tree helps test building without pushing changes
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - pypy
    # On channel https://anaconda.org/numba/
    - llvmdev 3.9*
  run:
    - pypy

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
