{% set shortversion = "13.0" %}
{% set version = "13.0.1" %}
{% set sha256_llvm = "ec6b80d82c384acad2dc192903a6cf2cdbaffb889b84bfb98da9d71e630fc834" %}
{% set sha256_lld = "666af745e8bf7b680533b4d18b7a31dc7cab575b1e6e4d261922bbafd9644cfb" %}
{% set build_number = "5" %}

package:
  name: llvmdev
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/llvm-{{ version }}.src.tar.xz
    fn: llvm-{{ version }}.src.tar.xz
    sha256: {{ sha256_llvm }}
    patches:
    - ../llvm13-lto-static.patch

  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lld-{{ version }}.src.tar.xz
    fn: lld-{{ version }}.src.tar.xz
    sha256: {{ sha256_lld }}
    folder: tools/lld

build:
  number: {{ build_number }}
  script_env:
    - PY_VCRUNTIME_REDIST
  ignore_run_exports:
    # Is static-linked
    - xar

requirements:
  build:
    # We cannot do this on macOS or windows
    # OSX already has llvm so has to be handled
    # at build.sh time
    # Windows needs to build using vs2015_runtime
    # irrespective of python version
    - {{ compiler('c') }} # [unix and not (armv6l or armv7l)]
    - {{ compiler('cxx') }} # [unix and not (armv6l or armv7l)]
    - cmake
    - make # [unix and not (armv6l or armv7l or aarch64)]
    # Needed to unpack the source tarball
    - m2w64-xz  # [win]
    # Needed to build LLVM
    - python >=3
  host:
    # needed for llc at runtime
    - zlib # [not win]
    - xar # [osx and x86_64]
    # llvm-lit testing needs *a* python
    - python # [not (armv6l or armv7l or aarch64 or win)]

test:
  files:
    - numba-3016.ll
  commands:
    - $PREFIX/bin/llvm-config --libs                         # [not win]
    - $PREFIX/bin/llc -version                               # [not win]

    - if not exist %LIBRARY_INC%\\llvm\\Pass.h exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\LLVMSupport.lib exit 1     # [win]

    - test -f $PREFIX/include/llvm/Pass.h                    # [unix]
    - test -f $PREFIX/lib/libLLVMSupport.a                   # [unix]

    - test -f $PREFIX/lib/libLLVMCore.a                      # [not win]

    # LLD tests
    - ld.lld --version                                       # [unix]
    - lld-link /?                                            # [win]

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
